{{- if .Values.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden-k8s-secrets-manager.name" . }}
  namespace: {{ include "bitwarden-k8s-secrets-manager.namespaceName" . }}
  labels:
    {{- include "bitwarden-k8s-secrets-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bitwarden-k8s-secrets-manager.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bitwarden-k8s-secrets-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: operator
        image: {{ include "bitwarden-k8s-secrets-manager.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.extraEnvs }}
        env:
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "bitwarden-k8s-secrets-manager.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
