apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwardensecrets.bitwarden-k8s-secrets-manager.demo.redhat.com
spec:
  group: bitwarden-k8s-secrets-manager.demo.redhat.com
  names:
    kind: BitwardenSecret
    listKind: BitwardenSecretList
    plural: bitwardensecrets
    singular: bitwardensecret
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              secrets:
                type: array
                items:
                  type: object
                  required:
                  - data
                  - name
                  properties:
                    annotations:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          key:
                            type: string
                          secret:
                            type: string
                          value:
                            type: string
                          project:
                            type: string
                        required:
                        - secret
                    data:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          key:
                            type: string
                          secret:
                            type: string
                          value:
                            type: string
                          project:
                            type: string
                        required:
                        - secret
                    labels:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          key:
                            type: string
                          secret:
                            type: string
                          value:
                            type: string
                          project:
                            type: string
                        required:
                        - secret
                    name:
                      type: string
                    namespace:
                      type: string
                    type:
                      type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              secret:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  resourceVersion:
                    type: string
                  uid:
                    type: string
              lastSync:
                type: string
                format: date-time
                description: "The date and time of the last successful synchronization with Bitwarden."
              lastSyncStatus:
                type: string
                description: "Status of the last synchronization attempt (e.g., 'Success', 'Failed')."
              lastErrorMessage:
                type: string
                description: "Detailed error message in case of failure in the last synchronization."
    served: true
    storage: true
